config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # GET /about
  root to: "main#index"
  get "about", to: "about#index"
  get "contact", to: "contact#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
# email: string
# password_digest:string
#
# password:string virtual
# password_confirmation: string virtual

class User < ApplicationRecord
    has_secure_password #rails method
    validates :email, presence: true, format: {with: /.+\@.+\..+/, message: "must be a valid email address you dummy"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated!"
        else
            render :edit
        end
    end

    private 

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        puts "hello!"
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account"
        else
            render :new
        end
    end

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out"
    end

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="text-center">
    <h1 class="text-3xl lg:text-6xl leading-tight max-w-3xl font-bold tracking-tight mt-6 mx-auto">About Coming Soon</h1>
</div>

app/views/contact/index.html.erb
<div class="text-center">
    <h1 class="text-3xl lg:text-6xl leading-tight max-w-3xl font-bold tracking-tight mt-6 mx-auto">Contact Coming Soon</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Deep-Dive</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="relative z-10 h-0.5 bg-gradient-to-r from-[#9867f0] to-[#ed4e50]"></div>
    <div class="absolute top-0 h-24 w-2/3">
     <img src="assets/tailwindBlur.png" />
    </div>
    <%= render partial: "shared/navbar" %>
    <div class="relative z-10">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="py-4 lg:py-16 flex items-center px-6">
  <div class="text-center mx-auto inline-block">
    <h1 class="text-3xl lg:text-6xl leading-tight max-w-3xl font-bold tracking-tight mt-6 mx-auto">Ruby.  On Rails.</h1>
    <div class="my-8 p-0.5 z-1 rounded-full relative bg-gradient-to-r from-[#9867f0] to-[#ed4e50] inline-flex items-center justify-center">
      <div class=" h-full w-full bg-white rounded-full px-6 py-2">
        <span class="z-10 text-sm lg:text-base bg-clip-text text-transparent bg-gradient-to-r from-[#9867f0] to-[#ed4e50] font-semibold relative -top-px">
          With Tailwind
        </span>
      </div>
    </div>
    <div class="max-w-3xl mx-auto lg:text-xl text-gray-600 mt-3 leading-normal font-light">
      <span class="font-bold">Michael Jordan:&nbsp;</span>I've missed more than 9000 shots in my career. I've lost almost 300 games.
      26 times, I've been trusted to take the game winning shot and missed. I've failed 
      over and over and over again in my life. And that is why I succeed.
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice]  %>
    <div class="w-60 rounded bg-transparent border-gray-400 shadow-lg m-auto text-center px-6 py-3 relative z-10" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert]  %>
    <div class="w-60 rounded bg-transparent border-red-400 shadow-lg m-auto text-center px-6 py-3 relative z-10 absolute top-0 mb-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="relative z-10 mb-8 overflow-x-auto">
  <div class="flex items-center justify-center text-center py-4 overflow-x-auto">
    <a class="text-sm md:text-base mx-3 ease-in-out duration-200 hover:text-[#ed4e50] font-bold" aria-current="page" href="/">Home</a>
    <%= link_to "Contact", contact_path, class: "text-sm md:text-base mx-3 ease-in-out duration-200 hover:text-[#ed4e50] font-bold"  %>
    <%= link_to "About", about_path, class: "text-sm md:text-base mx-3 ease-in-out duration-200 hover:text-[#ed4e50] font-bold"  %>
      <% if Current.user %>
      <div class="hidden md:flex">
        <%= link_to Current.user.email, edit_password_path, class: "underline" %>
      </div>
      <%= button_to "Logout", logout_path, class: "text-sm md:text-base mx-3 ease-in-out duration-200 hover:text-[#ed4e50] font-bold", method: :delete %>
    <% else %>
      <%= link_to "Sign In", sign_in_path, class: "text-sm md:text-base mx-3 ease-in-out duration-200 hover:text-[#ed4e50] font-bold" %>
      <%= link_to "Sign Up", sign_up_path, class: "text-sm md:text-base mx-3 ease-in-out duration-200 hover:text-[#ed4e50] font-bold" %>
    <% end %>
  <div>
</nav>